services:
  postgres:
    image: postgres:15
    container_name: ais_postgres
    environment:
      POSTGRES_USER: ais_user
      POSTGRES_PASSWORD: ais_password
      POSTGRES_DB: ais_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  trino:
    image: trinodb/trino:latest
    container_name: ais_trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino

  ais-core:
    build: ./ais-core
    container_name: ais_core
    ports:
      - "5000:5000"
    volumes:
      - ./ais-core/app:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ais_user
      - DB_PASSWORD=ais_password
      - DB_NAME=ais_db
    depends_on:
      - postgres
      - trino

volumes:
  postgres_data: