version: "3.8"

services:
  # 1. PostgreSQL (Hive & AIS metadata)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ais
      POSTGRES_PASSWORD: aispassword
      POSTGRES_DB: ais_pg_hub_metastore_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ais -d ais_pg_hub_metastore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. MinIO (object-storage / lake buckets)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9500:9000"
      - "9551:9001"
    volumes:
      - minio_data:/data

  # 3. Hive Metastore (patched) — ARM-ready
  hive-metastore:
    platform: linux/arm64
    build: ./hive-metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: metastore
      DB_TYPE: postgres
      # Override any derby defaults
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://postgres:5432/ais_pg_hub_metastore_db"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: "ais"
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: "aispassword"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "59083:9083"
    volumes:
      - ./hive-metastore/warehouse:/opt/hive/warehouse

  trino:
    platform: linux/arm64
    image: trinodb/trino:latest
    ports:
      - "58080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/var/trino/data 
    depends_on:
      - postgres
      - minio
      - hive-metastore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ui/"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped  # Add auto-restart
    
  # 5. Spark (with Iceberg JARs)
  spark:
    platform: linux/arm64
    build: ./spark
    environment:
      SPARK_MASTER: local[*]
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      HADOOP_HOME: /opt/hadoop
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/conf:/opt/spark/conf
    ports:
      - "55900:4040"
    depends_on:
      - hive-metastore
      - minio

  # 6. AIS Core API
  ais-core:
    platform: linux/arm64
    build: ./ais-core
    volumes:
      - ./ais-core/app:/app
    ports:
      - "55500:5000"
    depends_on:
      - postgres
      - trino
      - minio
      - hive-metastore

volumes:
  postgres_data:
  minio_data: